spring.application.name=erpvn
spring.datasource1.jdbc-url= jdbc:postgresql://103.74.121.154:5433/ebiz.metadata
spring.datasource1.username=admin
spring.datasource1.password=123456a@A
spring.datasource1.driver-class-name=org.postgresql.Driver
server.port=8878

spring.jpa.database1.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
springdoc.scalar.ui.path=/scalar-ui.html

scalar.enabled=true
spring.jpa.hibernate.ddl-auto=none 
spring.jpa.show-sql=true
spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379
redis.key=redis_xm